INSERT INTO category (name) VALUES ('Laptops');
INSERT INTO category (name) VALUES ('Cameras');
INSERT INTO category (name) VALUES ('TV');
INSERT INTO category (name) VALUES ('Phones');
INSERT INTO category (name) VALUES ('Monitors');
INSERT INTO category (name) VALUES ('Headphones');
INSERT INTO category (name) VALUES ('Speakers');
INSERT INTO category (name) VALUES ('Printers');
INSERT INTO category (name) VALUES ('Gaming');
